INSERT books (book_name, author_name, year, picture)
VALUES ('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', 'Андрей Богуславский', '2020', '../../static/Images/22.jpg'),
       ('Программирование на языке Go!', 'Марк Саммерфильд', '2008', '../../static/Images/23.jpg'),
       ('Толковый словарь сетевых терминов и аббревиатур', 'М. Вильямс', '1998', '../../static/Images/25.jpg'),
       ('Python for Data Analysis', 'Уэс Маккинни', '2020', '../../static/Images/26.jpg'),
       ('Thinking in Java (4th Edition)', 'Брюс Эккель', '1990', '../../static/Images/27.jpg'),
       ('Introduction to Algorithms', 'Томас Кормен, Чарльз Лейзерсон, Рональд Ривест, Клиффорд Штайн', '2020',
        '../../static/Images/29.jpg'),
       ('JavaScript Pocket Reference', 'Дэвид Флэнаган', '1995', '../../static/Images/31.jpg'),
       ('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles', 'Гэри Маклин Холл',
        '2020', '../../static/Images/32.jpg'),
       ('SQL: The Complete Reference', 'Джеймс Р. Грофф', '2010', '../../static/Images/33.jpg'),
       ('PHP and MySQL Web Development', 'Люк Веллинг', '2002', '../../static/Images/34.jpg'),
       ('Статистический анализ и визуализация данных с помощью R', 'Сергей Мастицкий', '2003',
        '../../static/Images/35.jpg'),
       ('Computer Coding for Kid', 'Джон Вудкок', '2006', '../../static/Images/36.jpg'),
       ('Exploring Arduino: Tools and Techniques for Engineering Wizardry', 'Джереми Блум', '2000',
        '../../static/Images/37.jpg'),
       ('Программирование микроконтроллеров для начинающих и не только', 'А. Белов', '2007',
        '../../static/Images/38.jpg'),
       ('The Internet of Things', 'Сэмюэл Грингард', '1999', '../../static/Images/39.jpg'),
       ('Sketching User Experiences: The Workbook', 'Сет Гринберг', '1900', '../../static/Images/40.jpg'),
       ('InDesign CS6', 'Александр Сераков', '1998', '../../static/Images/41.jpg'),
       ('Адаптивный дизайн. Делаем сайты для любых устройств', 'Тим Кедлек', '2001', '../../static/Images/42.jpg'),
       ('Android для разработчиков', 'Пол Дейтел, Харви Дейтел', '2001', '../../static/Images/43.jpg'),
       ('Clean Code: A Handbook of Agile Software Craftsmanship', 'Роберт Мартин', '2003',
        '../../static/Images/44.jpg'),
       ('ESwift Pocket Reference: Programming for iOS and OS X', 'Энтони Грей', '2004', '../../static/Images/45.jpg'),
       ('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence',
        'Мартин Фаулер, Прамодкумар Дж. Садаладж', '2000', '../../static/Images/46.jpg'),
       ('Head First Ruby', 'Джей Макгаврен', '2000', '../../static/Images/47.jpg'),
       ('Practical Vim', 'Дрю Нейл', '2000', '../../static/Images/48.jpg');
